server:
  port: 8001
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            #token-uri: http://localhost:8780/auth/realms/ng/protocol/openid-connect/token
            token-uri: https://localhost:8443/auth/realms/ng/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: caller
            client-secret: 8673caca-b67f-4db2-87ea-732de5f01dd6
            authorization-grant-type: client_credentials
ssl:
  keycloak:
    enabled: true
    truststore: classpath:keycloak-truststore.p12
    truststore-password: secret
  callee:
    enabled: true
    truststore: classpath:callee-truststore.p12
    truststore-password: secret
logging:
  level:
    org:
      springframework: info